storeFile=app/photo_kit.jks
storePassword=123456
keyAlias=test
keyPassword=123456
playLicensePublicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsfN60bm6zICeP7X2//aBtd2XJRCtV35xu9ggHEHz2+6WkGcYOtCgVSYCbK5/0DH2fAOIjipOoXJOSOaHXtoivwB8hUPpme8JzYFeJ+YpK1CJ69uSHcClPNVwByUZeyYmH0Hp4aTkiQVW7+tsYjwPZIjWSCBOQSz+REwodmuV3+xOKCo8k1VH6DXbr31r2vFbOI8gtuPNYq/Or8CQOGQ1p637PLPi9BbT2OdvyOt6SaqCBgliW1b6ogjOUICYJrBNLlrY6l6+PQj84jpZxqcai8NFfpaM5SrqqnYgRimDWiZGUSC/WrJ2DgbxTVvH47j6sG4ZUzQpNLOWab165PEAlQIDAQAB
