pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri('https://jitpack.io')
            def jitpackToken = providers.gradleProperty('authToken').orNull
                    ?: providers.environmentVariable('JITPACK_TOKEN').orNull
            if (jitpackToken) {
                credentials {
                    username = jitpackToken
                    password = ''
                }
            }
        }
    }
}

rootProject.name = 'Local Signage'

include ':app'
include ':core:core_base'
include ':core:core_utils'
include ':core:core_google'
include ':feature:feature_app'
include ':feature:feature_res'
