plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = 'com.wkq.localsignage.feature.app'
    compileSdk = libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk = libs.versions.minSdk.get().toInteger()
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation project(':core:core_base')
    implementation project(':core:core_google')
    implementation project(':core:core_utils')
    implementation project(':feature:feature_res')
    implementation libs.androidx.core.ktx
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.recyclerview
    implementation libs.material
    api libs.androidx.viewpager2
    implementation libs.coil
    implementation libs.gson
    implementation libs.ktor.server.core
    implementation libs.ktor.server.cio
    implementation libs.ktor.server.websockets
    implementation libs.zxing.core
    implementation libs.media3.exoplayer
    implementation libs.media3.exoplayer.hls
    implementation libs.media3.exoplayer.dash
    implementation libs.media3.exoplayer.rtsp
    implementation libs.media3.ui
    testImplementation libs.junit4
}
