package com.wkq.google.billing.gate

enum class GoogleFeatureAccessReason {
    GATE_DISABLED,
    GLOBAL_OPEN_ALL,
    LOG_ONLY,
    NO_RULE,
    FREE_FEATURE,
    PRO_ACTIVE,
    SUBSCRIPTION_ACTIVE,
    LIFETIME_ACTIVE,
    PRODUCT_OWNED,
    LIMIT_NOT_REACHED,
    PRO_REQUIRED,
    SUBSCRIPTION_REQUIRED,
    LIFETIME_REQUIRED,
    PRODUCT_REQUIRED,
    LIMIT_EXCEEDED,
    USAGE_REQUIRED,
    ENTITLEMENT_UNKNOWN
}
